config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("entrenaminto_sebastian.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("telefonos/", include("entrenaminto_sebastian.telefonera_app.urls")),
    path("movies/", include("entrenaminto_sebastian.movies_app.urls"))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

entrenaminto_sebastian/movies_app/urls.py
from django.urls import path
from entrenaminto_sebastian.movies_app.views import movies

app_name = "movies_app"

urlpatterns = [
    path('', movies.MoviesListView.as_view(), name='movies-list'),
    path('create/', movies.MoviesCreateView.as_view(), name='movies-create'),
    path('detail/<int:pk>', movies.MoviesDetailView.as_view(), name='movies-detail'),
    path('update/<int:pk>', movies.MoviesUpdateView.as_view(), name='movies-update'),
    path('delete/<int:pk>', movies.MoviesDeleteView.as_view(), name='movies-delete'),
]

entrenaminto_sebastian/telefonera_app/urls.py
from django.urls import path
from entrenaminto_sebastian.telefonera_app.views import telefonera

app_name = "telefonera_app"

urlpatterns = [
    path('', telefonera.TelefonoListView.as_view(), name='telefonera-list'),
    path('create/', telefonera.TelefonoCreateView.as_view(), name='telefonera-create'),
    path('detail/<int:pk>', telefonera.TelefonoDetailView.as_view(), name='telefonera-detail'),
    path('update/<int:pk>', telefonera.TelefonoUpdateView.as_view(), name='telefonera-update'),
    path('delete/<int:pk>', telefonera.TelefonoDeleteView.as_view(),name='telefonera-delete'),
]

entrenaminto_sebastian/users/urls.py
from django.urls import path

from entrenaminto_sebastian.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

entrenaminto_sebastian/movies_app/models.py
from django.db import models
from model_utils.fields import StatusField
from versatileimagefield.fields import VersatileImageField
from versatileimagefield.image_warmer import VersatileImageFieldWarmer

# Create your models here.

class Year(models.Model):
    year = models.CharField(max_length=4)

    def __str__(self):
        return u'%s' % (self.year)

class Movie(models.Model):
    nombre = models.CharField(max_length=100)
    año = models.ForeignKey( Year, on_delete=models.CASCADE, null=True, blank=True)
    director = models.CharField(max_length=100)
    poster = VersatileImageField(
        'Poster',
        upload_to='images/poster',
        blank=True,
        null=True,
        help_text='Insertar poster en formato .jpeg or .png | Tamaño máximo: 10 MB | Dimensiones recomendadas: 1372 x 772 px'
    )

    def __str__(self):
        return u'%s' % (self.nombre)

entrenaminto_sebastian/telefonera_app/models.py
from django.db import models
from model_utils import Choices
from model_utils.fields import StatusField
from versatileimagefield.fields import VersatileImageField
from versatileimagefield.image_warmer import VersatileImageFieldWarmer

class Telefono(models.Model):
    TIPO_CHOICES = Choices('Familia', 'Trabajo')
    tipo = StatusField(choices_name='TIPO_CHOICES')
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=20)

    foto = VersatileImageField(
        'Foto',
        upload_to='images/foto',
        blank=True,
        null=True,
        help_text='formato de imagen .jpeg or .png tamańo máximo: 10 MB dimensiones recomendadas: 1372 x 772 px'
    )

    class Meta:
        ordering = ['pk']

entrenaminto_sebastian/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Entrenaminto Sebastian.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

entrenaminto_sebastian/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

entrenaminto_sebastian/movies_app/views/movies.py
# store/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# specific to this view
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.urls import reverse_lazy
from braces.views import LoginRequiredMixin
from entrenaminto_sebastian.movies_app.models import Movie

class MoviesListView(ListView):
    model = Movie
    template_name = 'movies_app/list.html'
    context_object_name = 'movies'
    paginate_by = 5

class MoviesCreateView(LoginRequiredMixin, CreateView):
    model = Movie
    template_name = 'movies_app/forms.html'
    fields = ('nombre', 'año', 'director', 'poster')
    success_url = reverse_lazy('movies_app:movies-list')

class MoviesDetailView(DetailView):
    model = Movie
    template_name = 'movies_app/detail.html'
    context_object_name = 'movie'

class MoviesUpdateView(LoginRequiredMixin, UpdateView):
    model = Movie
    template_name = 'movies_app/forms.html'
    context_object_name = 'movie'
    fields = ('nombre', 'año', 'director', 'poster')

    def get_success_url(self):
        return reverse_lazy('movies_app:movies-list')

class MoviesDeleteView(LoginRequiredMixin, DeleteView):
    model = Movie
    context_object_name = 'movie'
    template_name = 'movies_app/confirm_delete.html'
    success_url = reverse_lazy('movies_app:movies-list')

entrenaminto_sebastian/telefonera_app/views/telefonera.py
# store/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# specific to this view
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.urls import reverse_lazy
from braces.views import LoginRequiredMixin

from entrenaminto_sebastian.telefonera_app.models import Telefono


class TelefonoListView(ListView):

    model = Telefono
    template_name = 'telefonera_app/telefonos/list.html'
    context_object_name = 'telefonos'
    paginate_by = 5
    
    '''
    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        books = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(books, self.paginate_by)
        try:
            books = paginator.page(page)
        except PageNotAnInteger:
            books = paginator.page(1)
        except EmptyPage:
            books = paginator.page(paginator.num_pages)
        context['books'] = books
        return context
    '''    

class TelefonoCreateView(LoginRequiredMixin, CreateView):
    model = Telefono
    template_name = 'telefonera_app/telefonos/form.html'
    fields = ('tipo', 'nombre', 'telefono', 'foto')
    success_url = reverse_lazy('telefonera_app:telefonera-list')


class TelefonoDetailView(DetailView):

    model = Telefono
    template_name = 'telefonera_app/telefonos/detail.html'
    context_object_name = 'telefono'


class TelefonoUpdateView(LoginRequiredMixin, UpdateView):

    model = Telefono
    template_name = 'telefonera_app/telefonos/form.html'
    context_object_name = 'telefono'
    fields = ('tipo', 'nombre', 'telefono', 'foto')

    def get_success_url(self):
        return reverse_lazy('telefonera_app:telefonera-list')


class TelefonoDeleteView(LoginRequiredMixin, DeleteView):
    model = Telefono
    context_object_name = 'telefono'
    template_name = 'telefonera_app/telefonos/confirm_delete.html'
    success_url = reverse_lazy('telefonera_app:telefonera-list')

entrenaminto_sebastian/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

entrenaminto_sebastian/templates/telefonera_app/telefonos/confirm_delete.html
{% extends "base.html" %}
{% block content %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Eliminar del telefono #{{book.id}}</h5>
    </div>
    <div class="card-body">
    <dl class="row">
      <dt class="col-sm-3">Nombre</dt>
      <dd class="col-sm-9">{{ telefono.nombre }}</dd>
      <dt class="col-sm-3">Telefono</dt>
      <dd class="col-sm-9">{{ telefono.telefono }}</dd>
      <dt class="col-sm-3">Tipo</dt>
      <dd class="col-sm-9">{{ telefono.tipo }}</dd>
    </dl>

    </div>

    <form method="post">
        {% csrf_token %}
        <div class="alert alert-warning" role="alert">
            Are you sure you want to delete <strong>{{ object }}</strong> ?
        </div>
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>

</div>

{% endblock %}

entrenaminto_sebastian/templates/telefonera_app/telefonos/detail.html
{% extends "base.html" %}
{% block content %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Detalle del telefono #{{book.id}}</h5>
    </div>
    <div class="card-body">
    <dl class="row">
      <dt class="col-sm-3">Foto</dt>
      <dd class="col-sm-9">
        {% if telefono.foto %}
        <img src="{{ telefono.foto.crop.200x200 }}" alt="Foto"/> <!--local.foto.crop.25x25  thumbnail-->
        {% else %}
        no foto
        {% endif %}
      </dd>
      <dt class="col-sm-3">Nombre</dt>
      <dd class="col-sm-9">{{ telefono.nombre }}</dd>
      <dt class="col-sm-3">Telefono</dt>
      <dd class="col-sm-9">{{ telefono.telefono }}</dd>
      <dt class="col-sm-3">Tipo</dt>
      <dd class="col-sm-9">{{ telefono.tipo }}</dd>
    </dl>

    </div>
</div>

{% endblock %}

entrenaminto_sebastian/templates/telefonera_app/telefonos/form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Crear nuevo telefono</h5>
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-success">Grabar</button>
        </form>
    </div>
</div>
{% endblock %}

entrenaminto_sebastian/templates/telefonera_app/telefonos/list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'telefonera_app:telefonera-create' %}">Crear</a>
<br><br>

<div class="table-responsive m-b-40">
  <table class="table table-borderless table-data3">
    <tr>
      <thead class="thead-light">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Foto</th>
          <th scope="col">Nombre</th>
          <th scope="col">Telefono</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for telefono in telefonos %}
        <tr>
          <td><a href="{% url 'telefonera_app:telefonera-detail' telefono.pk %}">{{ telefono.pk }}</a></td>
          <td>
            {% if telefono.foto %}
            <img src="{{ telefono.foto.crop.40x40 }}" alt="Foto" />
            <!--local.foto.crop.25x25  thumbnail-->
            {% else %}
            no foto
            {% endif %}
          </td>
          <td>{{ telefono.nombre }}</td>
          <td>{{ telefono.telefono }}</td>
          <td>
            <a href="{% url 'telefonera_app:telefonera-update' telefono.pk %}" class="btn btn-primary">Actualizar</a>
            <a href="{% url 'telefonera_app:telefonera-delete' telefono.pk %}"
              class="btn btn-outline-danger">Eliminar</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
  </table>
</div>

{% if is_paginated %}
{% include "_pagination.html" %}
{% endif %}

{% endblock %}